"""empty message

Revision ID: 0113ffe0f136
Revises: 
Create Date: 2024-06-26 12:24:01.851979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0113ffe0f136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('to_remember', sa.String(), nullable=True),
    sa.Column('first_test', sa.SmallInteger(), nullable=True),
    sa.Column('second_test', sa.SmallInteger(), nullable=True),
    sa.Column('third_test', sa.SmallInteger(), nullable=True),
    sa.Column('fourth_test', sa.SmallInteger(), nullable=True),
    sa.Column('fifth_test', sa.SmallInteger(), nullable=True),
    sa.Column('sixth_test', sa.SmallInteger(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
