"""empty message

Revision ID: 3256a475a62a
Revises: 0113ffe0f136
Create Date: 2024-07-03 11:23:14.262342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3256a475a62a'
down_revision: Union[str, None] = '0113ffe0f136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('recommendations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'recommendations')
    # ### end Alembic commands ###
