"""empty message

Revision ID: fa2c3f3d3271
Revises: 3256a475a62a
Create Date: 2024-07-09 21:26:55.616937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2c3f3d3271'
down_revision: Union[str, None] = '3256a475a62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('moca', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'moca')
    op.drop_column('patients', 'age')
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###
