// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
//
// const inter = Manrope({ subsets: ["latin"] });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}><div className="bg-[hsl(210_100%_97%)]">{children}</div></body>
//     </html>
//   );
// }
